name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:

  # =========================
  # BUILD JOB
  # =========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download Maven dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean compile


  # =========================
  # SECURITY JOB
  # =========================
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Download Maven dependencies first.
      # This helps prevent Trivy from hitting Maven Central
      # repeatedly and getting HTTP 429.
      - name: Download Maven dependencies
        run: mvn dependency:resolve

      # =========================
      # TRIVY
      # =========================
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy vulnerability scan
        run: |
          trivy fs \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --format table \
            .

           # =========================
      # GITLEAKS
      # =========================
      - name: Install Gitleaks
        run: |
          sudo apt-get update
          sudo apt-get install -y gitleaks

      - name: Check Gitleaks version
        run: |
          gitleaks version

      - name: Gitleaks secret scan
        run: |
          gitleaks detect \
            --source . \
            --report-path gitleaks-report.json \
            --report-format json \
            --exit-code 1
